using EmeryNorthwind.Data;
using EmeryNorthwind.Models.Dtos;
using EmeryNorthwind.Models.Entities;
using EmeryNorthwind.Services.Mapping;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EmeryNorthwind.Controllers {
  [Route("api/[controller]")]
  [ApiController]
  public class CategoriesController : ControllerBase {
    private readonly ApplicationDbContext _context;
    private readonly CategoryMappingService _categoryMappingService;
    public CategoriesController(
      ApplicationDbContext context,
      CategoryMappingService categoryMappingService
    ) {
      _context = context;
      _categoryMappingService = categoryMappingService;
    }
    
    // /api/categories
    [HttpGet("")] 
    public async Task<ActionResult<List<CategoryDto>>> GetCategories() {
      var categories = await _context.Categories.ToListAsync();

      var categoriesDtoList = categories
        .Select(c => _categoryMappingService.MapToCategoryDto(c))
        .ToList();

      return Ok(categoriesDtoList);
    }
    
    // /api/categories/product-counts
    [HttpGet("product-counts")] 
    public async Task<ActionResult<List<Category>>> GetProductCounts() {
      var categories = await _context.Products
        .Include(p => p.Category)
        .GroupBy(p => p.Category.CategoryName ?? string.Empty) 
        .ToDictionaryAsync(p => p.Key, p => p.Count());
      
      return Ok(categories);
    }

    // /api/categories/sales-totals
    [HttpGet("sales-totals")]
    public async Task<ActionResult<List<Category>>> GetSalesTotals() {
      
      var categories = await _context.OrderDetails
        .Include(od => od.Product)
            .ThenInclude(p => p.Category)
        .GroupBy(od => od.Product.Category.CategoryName ?? string.Empty)
        .ToDictionaryAsync(od => od.Key, od => (double?)od.Sum(
            od => (od.Discount == 0 || od.Discount == null) ? od.Quantity * od.UnitPrice : od.Quantity * (od.UnitPrice * (1 - od.Discount))
        ) ?? 0.0);


      // This code was generated by AI to round to 2 decimal places
      // I tried for so long to get it to round in the above but kept running into errors using the .Math.Round() method

      foreach (var value in categories.Values.ToList()) { // Create a copy of the values collection
          categories[categories.Keys.ToList().First(k => categories[k] == value)] = Math.Round(value, 2); // Assign the rounded value back to the original dictionary key-value pair
      }        
      
      return Ok(categories);
    }

  }
}